### ISSUE TITLE
Activity 메뉴 만들기

### ISSUE THREAD

**Issue by hanSong2** [woowa-techcamp-2020/todo-11#42]
- [x] Activity 컴포넌트 만들기
- [x] ActivityList 컴포넌트 만들기
- [x] Menu 컴포넌트 만들기

## Activity

- 각각의 Activity 는 하나의 사용자 액션을 표시한다.
- 액션 종류는 추가(add), 삭제(remove), 변경(update), 이동(move) 네 가지가 있다.
- 액션이 발생한 **시간**이 표시되어야 한다.
- 중요 키워드는 디자인의 변경을 줘서 **하이라이트** 시켜서 표현한다.

## ActivityList

- 지금까지 했던 모든 사용자 액션 기록이 위에서부터 최신 순으로 표시된다.
- 기록이 많아지면 레이어 오른쪽에 스크롤이 생긴다.
- 리스트를 펴고 접을 수 있다. 최초에는 펼쳐진 상태이다.

## Menu

- 헤더의 메뉴 버튼을 클릭하면, 오른쪽에서 메뉴 레이어가 **에니메이션 효과**와 함께 왼쪽 방향으로 나온다.
- 닫기 버튼을 클릭하면 메뉴 레이어가 다시 **에니메이션 효과**와 함께 오른쪽 방향으로 나온다.

**Comment by brightchul** [comment]
```
[
{
    email: string,
    action: string,
    content: string,
    fromColumnTItle: string,
    toColumnTitle: string,
    createdAt: Date
}
, ....
]
```

**Comment by hanSong2** [comment]
Activity -> ActivityItem
